# Generated by Django 4.2.1 on 2023-05-19 00:15

from django.db import migrations, models


def create_default_products(apps, schema_editor):
    Product = apps.get_model("cart", "Product")
    potatoes = Product(pk=1, name="Potatoes", price=5, default_quantity=2, count=10)
    potatoes.save()
    carrots = Product(pk=2, name="Carrots", price=4, default_quantity=1, count=20)
    carrots.save()
    onions = Product(pk=3, name="Onions", price=2, default_quantity=1, count=30)
    onions.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(create_default_products)
    ]
